name = "GeoMakie"
uuid = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
authors = ["Anshul Singhvi"]
version = "0.1.15"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Proj4 = "9a7e659c-8ee8-5706-894e-f68f43bc57ea"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
AbstractPlotting = "0.15.8"
GLMakie = "0.1.24"
Colors = "0.12"
GeoInterface = "0.5"
GeometryBasics = "0.2, 0.3"
ImageMagick = "1"
Proj4 = "0.7"
Reexport = "0.2, 1.0"
StructArrays = "0.4"
julia = "1"

[extras]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GLMakie"]
