name = "GeoMakie"
uuid = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
authors = ["Anshul Singhvi"]
version = "0.1.14-DEV"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
EarCut = "5160dea5-cc57-53b0-be5f-ac191989508a"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
MakieLayout = "5a521ce4-ebb9-4793-b5b7-b334dfe8393c"
NASAEarthObservations = "9526e54e-4491-4e9f-a840-d78b79cb5e3b"
Proj4 = "9a7e659c-8ee8-5706-894e-f68f43bc57ea"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
AbstractPlotting = "0.10, 0.11"
Colors = "0"
EarCut = "2"
GeoInterface = "0.5"
GeoJSON = "0.5"
GeometryBasics = "0.2, 0.3"
Glob = "1"
ImageMagick = "1"
MakieLayout = "0.5, 0.6, 0.7, 0.8, 0.9"
NASAEarthObservations = "0"
Proj4 = "0"
Reexport = "0"
StructArrays = "0.4"
julia = "1"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
MakieGallery = "dbd62bd0-c9f5-5087-a2e1-f5c4bb0cec90"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GLMakie", "CairoMakie", "MakieGallery"]
