name = "GeoMakie"
uuid = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
authors = ["Anshul Singhvi"]
version = "0.1.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
EarCut = "5160dea5-cc57-53b0-be5f-ac191989508a"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
MakieLayout = "5a521ce4-ebb9-4793-b5b7-b334dfe8393c"
NASAEarthObservations = "9526e54e-4491-4e9f-a840-d78b79cb5e3b"
Proj4 = "9a7e659c-8ee8-5706-894e-f68f43bc57ea"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1.1"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CairoMakie"]
