[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
CairoMakie = "0.3"
